# Generated by Django 4.2.5 on 2023-10-09 12:43

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='device',
            name='platform',
        ),
        migrations.AddField(
            model_name='device',
            name='platforms',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('app', 'App'), ('web', 'Web')], default=None, max_length=10),
            preserve_default=False,
        ),
    ]
