# Generated by Django 4.2.5 on 2023-10-09 15:27

import ads.fields
import ads.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('devices', '0002_remove_device_platform_device_platforms'),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.URLField()),
                ('view_count', models.PositiveIntegerField(default=0)),
                ('age_from', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(80)])),
                ('age_to', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(80)])),
                ('text', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('image', ads.fields.WEBPField(upload_to=ads.models.video_folder, verbose_name='Image')),
                ('video', models.FileField(upload_to='video/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['MOV', 'avi', 'mp4', 'webm', 'mkv'])])),
                ('devices', models.ManyToManyField(to='devices.device', verbose_name='platforms')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Imput',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.URLField()),
                ('view_count', models.PositiveIntegerField(default=0)),
                ('age_from', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(80)])),
                ('age_to', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(80)])),
                ('image', ads.fields.WEBPField(upload_to=ads.models.imput_folder, verbose_name='Image')),
                ('devices', models.ManyToManyField(to='devices.device', verbose_name='platforms')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.URLField()),
                ('view_count', models.PositiveIntegerField(default=0)),
                ('age_from', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(80)])),
                ('age_to', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(80)])),
                ('text', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('image', ads.fields.WEBPField(upload_to=ads.models.banner_folder, verbose_name='Image')),
                ('devices', models.ManyToManyField(to='devices.device', verbose_name='platforms')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
