# Generated by Django 4.2.5 on 2023-09-27 07:33

import ads.fields
import ads.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [('ads', '0001_initial'), ('ads', '0002_alter_video_image')]

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('image', ads.fields.WEBPField(height_field='height', upload_to=ads.models.banner_folder, verbose_name='Image', width_field='width')),
                ('link', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Imput',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', ads.fields.WEBPField(height_field='height', upload_to=ads.models.imput_folder, verbose_name='Image', width_field='width')),
                ('link', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('image', ads.fields.WEBPField(upload_to=ads.models.video_folder, verbose_name='Image')),
                ('video', models.FileField(upload_to='video/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['MOV', 'avi', 'mp4', 'webm', 'mkv'])])),
                ('link', models.URLField()),
            ],
        ),
    ]
