# Generated by Django 4.2.5 on 2023-11-06 14:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='cycle_duration',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(60)]),
        ),
    ]
