# Generated by Django 4.2.5 on 2023-10-25 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='skip_duration',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
