# Generated by Django 4.2.5 on 2023-11-29 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('hidden', 'Hidden'), ('converting', 'Converting'), ('completed', 'Completed'), ('deleted', 'Deleted'), ('test', 'Test')], default='converting', max_length=30),
        ),
    ]
