# Generated by Django 4.2.5 on 2023-11-07 09:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0002_alter_banner_cycle_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='cycle_duration',
            field=models.PositiveIntegerField(default=180, validators=[django.core.validators.MinValueValidator(60)]),
        ),
    ]
