# Generated by Django 4.2.5 on 2023-10-04 16:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0002_banner_age_from_banner_age_to_imput_age_from_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='age_from',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(80)]),
        ),
        migrations.AlterField(
            model_name='banner',
            name='age_to',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(80)]),
        ),
        migrations.AlterField(
            model_name='imput',
            name='age_from',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(80)]),
        ),
        migrations.AlterField(
            model_name='imput',
            name='age_to',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(80)]),
        ),
        migrations.AlterField(
            model_name='video',
            name='age_from',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(80)]),
        ),
        migrations.AlterField(
            model_name='video',
            name='age_to',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(80)]),
        ),
    ]
