# Generated by Django 4.2.5 on 2023-10-02 13:28

import ads.fields
import ads.models
from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [('ads', '0003_alter_banner_image_alter_imput_image'), ('ads', '0004_alter_imput_image_alter_video_image'), ('ads', '0005_alter_banner_image_alter_imput_image_and_more'), ('ads', '0006_alter_banner_image_alter_imput_image')]

    dependencies = [
        ('ads', '0001_initial_squashed_0002_alter_video_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='image',
            field=models.ImageField(upload_to=ads.models.banner_folder, verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='imput',
            name='image',
            field=ads.fields.WEBPField(upload_to=ads.models.imput_folder, verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='imput',
            name='image',
            field=models.ImageField(upload_to=ads.models.imput_folder, verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='video',
            name='image',
            field=models.ImageField(upload_to=ads.models.video_folder, verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='image',
            field=ads.fields.WEBPField(height_field='height', upload_to=ads.models.banner_folder, verbose_name='Image', width_field='width'),
        ),
        migrations.AlterField(
            model_name='imput',
            name='image',
            field=ads.fields.WEBPField(height_field='height', upload_to=ads.models.imput_folder, verbose_name='Image', width_field='width'),
        ),
        migrations.AlterField(
            model_name='video',
            name='image',
            field=ads.fields.WEBPField(upload_to=ads.models.video_folder, verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='image',
            field=ads.fields.WEBPField(upload_to=ads.models.banner_folder, verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='imput',
            name='image',
            field=ads.fields.WEBPField(upload_to=ads.models.imput_folder, verbose_name='Image'),
        ),
    ]
