# Generated by Django 4.2.5 on 2023-10-27 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0002_alter_video_skip_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='devices',
            field=models.ManyToManyField(to='ads.device', verbose_name='advertisement'),
        ),
        migrations.AlterField(
            model_name='imput',
            name='devices',
            field=models.ManyToManyField(to='ads.device', verbose_name='advertisement'),
        ),
        migrations.AlterField(
            model_name='video',
            name='devices',
            field=models.ManyToManyField(to='ads.device', verbose_name='advertisement'),
        ),
    ]
