# Generated by Django 4.2.5 on 2023-12-08 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0002_alter_video_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='language',
            field=models.CharField(choices=[('tm', 'Turkmen'), ('ru', 'Russian'), ('en', 'English'), ('tr', 'Turkish')], default='tm', max_length=15),
        ),
        migrations.AddField(
            model_name='imput',
            name='language',
            field=models.CharField(choices=[('tm', 'Turkmen'), ('ru', 'Russian'), ('en', 'English'), ('tr', 'Turkish')], default='tm', max_length=15),
        ),
        migrations.AddField(
            model_name='video',
            name='language',
            field=models.CharField(choices=[('tm', 'Turkmen'), ('ru', 'Russian'), ('en', 'English'), ('tr', 'Turkish')], default='tm', max_length=15),
        ),
    ]
