# Generated by Django 4.2.5 on 2023-12-28 07:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0003_banner_language_imput_language_video_language'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='cycle_duration',
            field=models.PositiveIntegerField(default=180, validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
