# Generated by Django 4.2.7 on 2023-11-09 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0003_alter_banner_cycle_duration'),
    ]

    operations = [
        migrations.RenameField(
            model_name='banner',
            old_name='age_from',
            new_name='max_age',
        ),
        migrations.RenameField(
            model_name='banner',
            old_name='age_to',
            new_name='min_age',
        ),
        migrations.RenameField(
            model_name='imput',
            old_name='age_from',
            new_name='max_age',
        ),
        migrations.RenameField(
            model_name='imput',
            old_name='age_to',
            new_name='min_age',
        ),
        migrations.RenameField(
            model_name='video',
            old_name='age_from',
            new_name='max_age',
        ),
        migrations.RenameField(
            model_name='video',
            old_name='age_to',
            new_name='min_age',
        ),
    ]
