# Generated by Django 4.2.5 on 2023-10-07 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0001_initial'),
        ('ads', '0003_alter_banner_age_from_alter_banner_age_to_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='platform',
            field=models.ManyToManyField(to='devices.device', verbose_name='ads'),
        ),
        migrations.AddField(
            model_name='imput',
            name='platform',
            field=models.ManyToManyField(to='devices.device', verbose_name='ads'),
        ),
        migrations.AddField(
            model_name='video',
            name='platform',
            field=models.ManyToManyField(to='devices.device', verbose_name='ads'),
        ),
    ]
