# Generated by Django 4.2.5 on 2023-10-07 17:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0004_banner_platform_imput_platform_video_platform'),
    ]

    operations = [
        migrations.RenameField(
            model_name='banner',
            old_name='platform',
            new_name='platforms',
        ),
        migrations.RenameField(
            model_name='imput',
            old_name='platform',
            new_name='platforms',
        ),
        migrations.RenameField(
            model_name='video',
            old_name='platform',
            new_name='platforms',
        ),
    ]
