# Generated by Django 4.2.7 on 2023-11-11 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0001_initial'),
        ('ads', '0004_rename_age_from_banner_max_age_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='provinces',
            field=models.ManyToManyField(to='locations.province'),
        ),
        migrations.AddField(
            model_name='imput',
            name='provinces',
            field=models.ManyToManyField(to='locations.province'),
        ),
        migrations.AddField(
            model_name='video',
            name='provinces',
            field=models.ManyToManyField(to='locations.province'),
        ),
    ]
