# Generated by Django 4.2.5 on 2023-12-30 18:17

import ads.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0004_alter_banner_cycle_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='image',
            field=models.ImageField(upload_to=ads.models.banner_folder, verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='imput',
            name='image',
            field=models.ImageField(upload_to=ads.models.banner_folder, verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='video',
            name='image',
            field=models.ImageField(upload_to=ads.models.banner_folder, verbose_name='Image'),
        ),
    ]
