# Generated by Django 4.2.5 on 2023-10-07 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0001_initial'),
        ('ads', '0005_rename_platform_banner_platforms_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='platforms',
            field=models.ManyToManyField(to='devices.device', verbose_name='platforms'),
        ),
        migrations.AlterField(
            model_name='imput',
            name='platforms',
            field=models.ManyToManyField(to='devices.device', verbose_name='platforms'),
        ),
        migrations.AlterField(
            model_name='video',
            name='platforms',
            field=models.ManyToManyField(to='devices.device', verbose_name='platforms'),
        ),
    ]
