# Generated by Django 4.2.5 on 2023-11-18 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0005_banner_provinces_imput_provinces_video_provinces'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='devices',
            field=models.ManyToManyField(to='ads.device'),
        ),
        migrations.AlterField(
            model_name='imput',
            name='devices',
            field=models.ManyToManyField(to='ads.device'),
        ),
        migrations.AlterField(
            model_name='video',
            name='devices',
            field=models.ManyToManyField(to='ads.device'),
        ),
    ]
