# Generated by Django 4.2.5 on 2023-10-08 10:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0006_alter_banner_platforms_alter_imput_platforms_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='banner',
            old_name='platforms',
            new_name='devices',
        ),
        migrations.RenameField(
            model_name='imput',
            old_name='platforms',
            new_name='devices',
        ),
        migrations.RenameField(
            model_name='video',
            old_name='platforms',
            new_name='devices',
        ),
    ]
