# Generated by Django 4.2.5 on 2023-11-18 16:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0007_alter_banner_uuid_alter_imput_uuid_alter_video_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='skip_duration',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(3), django.core.validators.MaxValueValidator(20)]),
        ),
    ]
