# Generated by Django 4.2.5 on 2023-11-24 14:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0003_alter_city_options'),
        ('ads', '0010_alter_video_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='cities',
            field=models.ManyToManyField(to='locations.city'),
        ),
        migrations.AddField(
            model_name='imput',
            name='cities',
            field=models.ManyToManyField(to='locations.city'),
        ),
        migrations.AddField(
            model_name='video',
            name='cities',
            field=models.ManyToManyField(to='locations.city'),
        ),
        migrations.AlterField(
            model_name='video',
            name='video',
            field=models.FileField(upload_to='video/videos/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['MOV', 'avi', 'mp4', 'webm', 'mkv', 'm3u8'])]),
        ),
    ]
