# Generated by Django 4.2.5 on 2023-11-29 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0002_remove_city_code_name_city_slug_alter_city_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='province',
            name='code_name',
        ),
        migrations.AddField(
            model_name='province',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='city',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='province',
            name='name',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
